"""
tests/test_data_quality.py — Data Quality & Report Artifact Tests

Validates that pipeline-generated report artifacts (clustering results,
occupancy forecasts, feature importances) are present and meet minimum
quality thresholds.

Run:
    pytest tests/test_data_quality.py -v
"""

import pytest
import pandas as pd
import numpy as np
import os
import json


# ─────────────────────────────────────────────────────────────────────────────
# PATHS
# ─────────────────────────────────────────────────────────────────────────────
ENRICHED_PATH          = "data/processed/enriched_listings.csv"
FEATURE_IMPORTANCES    = "reports/feature_importances.csv"
OCCUPANCY_FORECAST     = "reports/occupancy_forecast.csv"
CLUSTER_LABELS_PATH    = "reports/cluster_labels.csv"
HYPOTHESIS_RESULTS     = "reports/hypothesis_results.md"
SUMMARY_STATS          = "reports/summary_stats.csv"
ALERTS_LOG             = "reports/stream_alerts.json"


# ─────────────────────────────────────────────────────────────────────────────
# REPORT ARTIFACT EXISTENCE
# ─────────────────────────────────────────────────────────────────────────────
class TestReportArtifactsExist:

    def test_feature_importances_exist(self):
        """ML pipeline must output feature_importances.csv."""
        assert os.path.exists(FEATURE_IMPORTANCES), (
            f"'{FEATURE_IMPORTANCES}' not found. Run 'python src/machine_learning.py'"
        )

    def test_occupancy_forecast_exists(self):
        """Occupancy forecast CSV must be generated by the ML pipeline."""
        assert os.path.exists(OCCUPANCY_FORECAST), (
            f"'{OCCUPANCY_FORECAST}' not found. Run 'python src/machine_learning.py'"
        )

    def test_hypothesis_results_exist(self):
        """Statistical analysis must produce hypothesis results."""
        assert os.path.exists(HYPOTHESIS_RESULTS), (
            f"'{HYPOTHESIS_RESULTS}' not found. Run 'python src/statistics_analysis.py'"
        )


# ─────────────────────────────────────────────────────────────────────────────
# FEATURE IMPORTANCES VALIDATION
# ─────────────────────────────────────────────────────────────────────────────
class TestFeatureImportances:

    @pytest.fixture(scope="class")
    def fi_df(self):
        if not os.path.exists(FEATURE_IMPORTANCES):
            pytest.skip(f"'{FEATURE_IMPORTANCES}' not found")
        return pd.read_csv(FEATURE_IMPORTANCES)

    def test_has_expected_columns(self, fi_df):
        """Feature importances must have 'feature' and 'importance' columns."""
        assert "feature" in fi_df.columns, "Missing 'feature' column"
        assert "importance" in fi_df.columns, "Missing 'importance' column"

    def test_minimum_feature_count(self, fi_df):
        """At least 5 features must be reported."""
        assert len(fi_df) >= 5, (
            f"Only {len(fi_df)} features reported — expected at least 5"
        )

    def test_importance_values_nonnegative(self, fi_df):
        """Feature importance values must be non-negative."""
        n_neg = (fi_df["importance"] < 0).sum()
        assert n_neg == 0, f"{n_neg} features have negative importance values"

    def test_importance_values_sum_to_one(self, fi_df):
        """For tree-based models, feature importances should sum to ~1.0."""
        total = fi_df["importance"].sum()
        assert 0.95 <= total <= 1.05, (
            f"Feature importances sum to {total:.3f} — expected ~1.0"
        )

    def test_top_feature_is_sensible(self, fi_df):
        """The top-ranked feature should be a known pricing-relevant feature."""
        known_pricing_features = {
            "latitude", "longitude", "room_type", "minimum_nights",
            "number_of_reviews", "review_scores_rating",
            "calculated_host_listings_count", "availability_365",
            "host_is_superhost", "accommodates", "bedrooms", "bathrooms"
        }
        top_feature = fi_df.sort_values("importance", ascending=False).iloc[0]["feature"]
        # This is a soft warning, not a hard failure — top feature varies by model
        # Just ensure it's not something clearly wrong like 'id'
        assert top_feature != "id", (
            f"Top feature is 'id' — this suggests target leakage in the model"
        )


# ─────────────────────────────────────────────────────────────────────────────
# OCCUPANCY FORECAST VALIDATION
# ─────────────────────────────────────────────────────────────────────────────
class TestOccupancyForecast:

    @pytest.fixture(scope="class")
    def forecast_df(self):
        if not os.path.exists(OCCUPANCY_FORECAST):
            pytest.skip(f"'{OCCUPANCY_FORECAST}' not found")
        return pd.read_csv(OCCUPANCY_FORECAST)

    def test_minimum_forecast_horizon(self, forecast_df):
        """Forecast must cover at least 6 future time periods."""
        assert len(forecast_df) >= 6, (
            f"Forecast only has {len(forecast_df)} rows — expected 6+ periods"
        )

    def test_has_date_column(self, forecast_df):
        """Forecast DataFrame must contain a date/time column."""
        date_cols = [c for c in forecast_df.columns if "date" in c.lower()
                     or "month" in c.lower() or "period" in c.lower()
                     or "time" in c.lower()]
        assert date_cols, (
            f"No date/time column found in forecast. Columns: {list(forecast_df.columns)}"
        )

    def test_forecast_values_bounded(self, forecast_df):
        """Occupancy/demand forecast values must be in a reasonable range."""
        # Find numeric columns excluding date columns
        numeric_cols = forecast_df.select_dtypes(include=[np.number]).columns.tolist()
        if not numeric_cols:
            pytest.skip("No numeric columns found in forecast")
        for col in numeric_cols:
            max_val = forecast_df[col].max()
            min_val = forecast_df[col].min()
            # Occupancy should be between 0 and 1, or revenue 0 to large positive
            assert min_val >= 0, (
                f"Column '{col}' has negative values ({min_val:.2f}) in forecast"
            )


# ─────────────────────────────────────────────────────────────────────────────
# CLUSTERING VALIDATION
# ─────────────────────────────────────────────────────────────────────────────
class TestClusteringOutput:

    @pytest.fixture(scope="class")
    def cluster_df(self):
        if not os.path.exists(CLUSTER_LABELS_PATH):
            pytest.skip(f"'{CLUSTER_LABELS_PATH}' not found. Run 'python src/clustering.py'")
        return pd.read_csv(CLUSTER_LABELS_PATH)

    def test_cluster_labels_nonempty(self, cluster_df):
        """Cluster labels file must not be empty."""
        assert len(cluster_df) > 0, "Cluster labels file is empty"

    def test_cluster_column_present(self, cluster_df):
        """A 'cluster' or 'segment' column must exist."""
        cluster_cols = [c for c in cluster_df.columns
                        if "cluster" in c.lower() or "segment" in c.lower()]
        assert cluster_cols, (
            f"No cluster/segment column found. Columns: {list(cluster_df.columns)}"
        )

    def test_minimum_cluster_count(self, cluster_df):
        """At least 2 clusters must be identified (otherwise clustering is trivial)."""
        cluster_cols = [c for c in cluster_df.columns
                        if "cluster" in c.lower() or "segment" in c.lower()]
        if not cluster_cols:
            pytest.skip("No cluster column found")
        n_clusters = cluster_df[cluster_cols[0]].nunique()
        assert n_clusters >= 2, (
            f"Only {n_clusters} cluster(s) found — clustering may have failed"
        )

    def test_no_null_cluster_labels(self, cluster_df):
        """No listing should have a null cluster assignment."""
        cluster_cols = [c for c in cluster_df.columns
                        if "cluster" in c.lower() or "segment" in c.lower()]
        if not cluster_cols:
            pytest.skip("No cluster column found")
        n_null = cluster_df[cluster_cols[0]].isna().sum()
        assert n_null == 0, f"{n_null} listings have null cluster labels"


# ─────────────────────────────────────────────────────────────────────────────
# STREAM ALERTS LOG VALIDATION
# ─────────────────────────────────────────────────────────────────────────────
class TestStreamAlertsLog:

    @pytest.fixture(scope="class")
    def alerts_data(self):
        if not os.path.exists(ALERTS_LOG):
            pytest.skip(
                f"'{ALERTS_LOG}' not found. "
                "Run 'python src/stream_processor.py' first."
            )
        with open(ALERTS_LOG) as f:
            return json.load(f)

    def test_alerts_structure(self, alerts_data):
        """Alert log must contain required top-level keys."""
        required_keys = {"simulation_run", "events_processed", "anomalies_detected", "alerts"}
        assert required_keys.issubset(set(alerts_data.keys())), (
            f"Missing keys in alerts log: {required_keys - set(alerts_data.keys())}"
        )

    def test_events_processed_positive(self, alerts_data):
        """Simulation must have processed at least 1 event."""
        assert alerts_data["events_processed"] > 0, "No events were processed"

    def test_alert_records_have_required_fields(self, alerts_data):
        """Each alert must have the required fields for downstream consumers."""
        required_fields = {
            "alert_id", "severity", "listing_id",
            "borough", "reported_price", "neighbourhood_median"
        }
        for i, alert in enumerate(alerts_data.get("alerts", [])):
            missing = required_fields - set(alert.keys())
            assert not missing, (
                f"Alert #{i} is missing fields: {missing}"
            )

    def test_severity_values_valid(self, alerts_data):
        """Alert severity must be either WARNING or CRITICAL."""
        valid_severities = {"WARNING", "CRITICAL"}
        for alert in alerts_data.get("alerts", []):
            assert alert["severity"] in valid_severities, (
                f"Invalid severity '{alert['severity']}' — "
                f"must be one of {valid_severities}"
            )
